version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/home/your_rpi_user/Docker/pigallery/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/home/your_rpi_user/Docker/nextcloud2/html/data/rejsikej/files/Photos:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "/home/your_rpi_user/Docker/pigallery/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 81:80
    restart: "no"

volumes:
  db-data:

###PIGALLERY

  pigallery2:
    image: bpatrik/pigallery2:latest #https://github.com/bpatrik/pigallery2
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - /home/Docker/pigallery/config:/app/data/config
      - /home/Docker/pigallery/tmp:/app/data/tmp
      - db_data:/app/data/db
      - /home/jalcocert/Desktop/pixel8pro:/app/data/images:ro #your images folder
      #- /mnt/ext4_drive/Syncthing_Pixel8:/app/data/images:ro #your images folder
      #- "/mnt/ext4_drive/Syncthing_Pixel8:/app/data/images:ro"
    ports:
      - 8088:80
    restart: unless-stopped

volumes:
  db_data:


version: '3'
services:
  pigallery-db:
    container_name: pigallery-db
    image: linuxserver/mariadb
    volumes:
      - /home/your_rpi_user/Docker/pigallery:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pigallery2_pass
      - MYSQL_USER=pigallery2
      - MYSQL_PASSWORD=pigallery2_pass
      - MYSQL_DATABASE=pigallery2

  pigallery2:
    image: bpatrik/pigallery2:latest
    command: sh -c 'bin/wait-for pigallery-db:3306 -- --Server-Database-mysql-host=pigallery-db --Server-Database-mysql-username=pigallery2 --Server-Database-mysql-password=pigallery2_pass --Server-Database-mysql-database=pigallery2'
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "/home/your_rpi_user/Docker/pigallery/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "/home/your_rpi_user/Docker/nextcloud2/html/data/rejsikej/files/Photos:/app/data/images:ro" # CHANGE ME, ':ro' mean read-only
      - "/home/your_rpi_user/Docker/pigallery/tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 81:80
    restart: always

volumes:
  db-data: