services:
  logseq:
    container_name: logseq
    image: ghcr.io/logseq/logseq-webapp:latest #https://github.com/logseq/logseq/pkgs/container/logseq-webapp
    ports:
      - "3037:80"  # Expose Logseq on port 80 (standard Nginx port in image)
    environment:
      - LOGSEQ_SERVER_PORT=80  # Match the Nginx listen port
    restart: unless-stopped
    #the container does not manage persistent storage, see the readme for more info
    # volumes:
    #   - ./logseq_data:/data

# Uncomment the following lines if you need persistent storage
# volumes:
  # logseq_data: