services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    ports:
      - "3037:3000"  # Expose Logseq on port 3000
    environment:
      - LOGSEQ_SERVER_PORT=3000  # Set the Logseq server port
    restart: unless-stopped
    volumes:
      - ./logseq_data:/data

# Uncomment the following lines if you need persistent storage
# volumes:
  # logseq_data: