http:
  middlewares:    
    default-security-headers:
      headers:
        customBrowserXSSValue: 0                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: false                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        contentSecurityPolicy: "default-src 'self'"     
        customRequestHeaders:
          X-Forwarded-Proto: https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

  routers: #for external services (outside the traefik network)
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.x300.jalcocertech.com`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      tls: {}
      service: portainer
    freshrss:
      entryPoints:
        - "https"
      rule: "Host(`freshrss.x300.jalcocertech.com`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      tls: {}
      service: freshrss      

  services:
    freshrss:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:8200" #without https and using the port of the host (not the container one)!
        passHostHeader: true  
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000" #or simply using the container name plus host port
        passHostHeader: true