version: "3.7"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - "59:53/udp"
      - "59:53/tcp"
      - "89:80/tcp"
      - "449:443/tcp"
      - "3009:3000/tcp" #UI      
      # Additional ports you may need:
      # - "67:67/udp"
      # - "68:68/tcp"
      # - "68:68/udp"
      # - "853:853/tcp"
    volumes:
      - /home/Docker/Adguard/config:/config
      - /home/Docker/Adguard/logs:/var/log/adguardhome
    restart: always
    networks:
      - traefik_traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.adguardhome.entrypoints=http"
      - "traefik.http.routers.adguardhome.rule=Host(`adguardhome.wal.jalcocertech.com`)" #Tweak this with your subdomain
      - "traefik.http.middlewares.adguardhome-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguardhome.middlewares=adguardhome-https-redirect"
      - "traefik.http.routers.adguardhome-secure.entrypoints=https"
      - "traefik.http.routers.adguardhome-secure.rule=Host(`adguardhome.wal.jalcocertech.com`)" #Tweak this with your subdomain
      - "traefik.http.routers.adguardhome-secure.tls=true"
      - "traefik.http.routers.adguardhome-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.adguardhome-secure.service=adguardhome"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"  ###the container port!!!!!
networks:
  traefik_traefik-proxy:
    external: true